import base64
import csv
import io
import json

from odoo import api, fields, models


class RgrReportJob(models.Model):
    _name = 'rgr.report.job'
    _description = 'Report Generation Job'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'generated_date desc, id desc'

    name = fields.Char(string='Job Name', required=True, tracking=True)
    template_id = fields.Many2one(
        comodel_name='rgr.report.template',
        string='Report Template',
        required=True,
        ondelete='restrict',
        tracking=True,
    )
    output_format = fields.Selection(
        selection=[
            ('pdf', 'PDF'),
            ('excel', 'Excel'),
            ('csv', 'CSV'),
        ],
        string='Output Format',
        required=True,
        default='pdf',
        tracking=True,
    )
    state = fields.Selection(
        selection=[
            ('draft', 'Draft'),
            ('generating', 'Generating'),
            ('done', 'Done'),
            ('failed', 'Failed'),
        ],
        string='State',
        default='draft',
        required=True,
        tracking=True,
    )
    file_data = fields.Binary(string='File', readonly=True, copy=False)
    file_name = fields.Char(string='File Name', readonly=True, copy=False)
    record_count = fields.Integer(
        string='Record Count',
        readonly=True,
        copy=False,
    )
    generated_by = fields.Many2one(
        comodel_name='res.users',
        string='Generated By',
        default=lambda self: self.env.user,
        readonly=True,
    )
    generated_date = fields.Datetime(
        string='Generated Date',
        default=fields.Datetime.now,
        readonly=True,
    )
    history_id = fields.Many2one(
        comodel_name='rgr.report.history',
        string='History Record',
        readonly=True,
        copy=False,
    )

    def action_run(self):
        """Generate the report file for each job in self."""
        for job in self:
            job.write({'state': 'generating'})
            try:
                file_data, file_name, record_count = job._generate_file()
                job.write({
                    'file_data': file_data,
                    'file_name': file_name,
                    'record_count': record_count,
                    'state': 'done',
                    'generated_date': fields.Datetime.now(),
                })
                job.template_id._log_generation()
                history = self.env['rgr.report.history'].create({
                    'name': job.name,
                    'template_id': job.template_id.id,
                    'job_id': job.id,
                    'file_name': file_name,
                    'file_size': len(base64.b64decode(file_data)) if file_data else 0,
                    'generated_date': fields.Datetime.now(),
                })
                job.write({'history_id': history.id})
            except Exception as exc:
                job.write({'state': 'failed'})
                raise
        return True

    def _get_records(self):
        """Return the recordset of the target model based on the template."""
        self.ensure_one()
        template = self.template_id
        target_model = self.env[template.model_name]
        domain = []
        if template.filter_domain:
            try:
                domain = json.loads(template.filter_domain)
            except (ValueError, TypeError):
                domain = []
        records = target_model.search(domain)
        if template.group_by:
            group_fields = [f.strip() for f in template.group_by.split(',') if f.strip()]
            if group_fields:
                records = records.sorted(group_fields)
        return records

    def _generate_file(self):
        """Produce the binary file content, file name and record count."""
        self.ensure_one()
        records = self._get_records()
        record_count = len(records)
        timestamp = fields.Datetime.now().strftime('%Y%m%d_%H%M%S')
        if self.output_format == 'csv':
            file_name = '%s_%s.csv' % (self.template_id.name, timestamp)
            file_data = self._render_csv(records)
        elif self.output_format == 'excel':
            file_name = '%s_%s.xlsx' % (self.template_id.name, timestamp)
            file_data = self._render_excel(records)
        else:
            file_name = '%s_%s.pdf' % (self.template_id.name, timestamp)
            file_data = self._render_pdf(records)
        return file_data, file_name, record_count

    def _get_columns(self, records):
        """Return a list of (field_name, label) tuples for the export."""
        self.ensure_one()
        columns = []
        config = self.template_id.template_config
        if config:
            try:
                parsed = json.loads(config)
                if isinstance(parsed, dict) and parsed.get('columns'):
                    for col in parsed['columns']:
                        if isinstance(col, dict):
                            columns.append((col.get('field'), col.get('label', col.get('field'))))
                        elif isinstance(col, str):
                            columns.append((col, col))
            except (ValueError, TypeError):
                pass
        if not columns and records:
            fields_meta = records.fields_get()
            for fname in list(fields_meta.keys())[:10]:
                columns.append((fname, fields_meta[fname].get('string', fname)))
        return columns

    def _render_csv(self, records):
        """Render records to a base64-encoded CSV file."""
        columns = self._get_columns(records)
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow([label for _, label in columns])
        for record in records:
            row = []
            for fname, _label in columns:
                value = getattr(record, fname, '')
                if value and hasattr(value, 'name'):
                    value = value.name
                row.append(value or '')
            writer.writerow(row)
        data = output.getvalue().encode('utf-8')
        return base64.b64encode(data)

    def _render_excel(self, records):
        """Render records to a base64-encoded Excel file (xlsx)."""
        try:
            from openpyxl import Workbook
        except ImportError:
            return self._render_csv(records).replace(
                b'.csv', b'.xlsx'
            ) if False else self._render_csv(records)
        columns = self._get_columns(records)
        workbook = Workbook()
        sheet = workbook.active
        sheet.title = 'Report'
        sheet.append([label for _, label in columns])
        for record in records:
            row = []
            for fname, _label in columns:
                value = getattr(record, fname, '')
                if value and hasattr(value, 'name'):
                    value = value.name
                row.append(value or '')
            sheet.append(row)
        buffer = io.BytesIO()
        workbook.save(buffer)
        buffer.seek(0)
        return base64.b64encode(buffer.read())

    def _render_pdf(self, records):
        """Render records to a base64-encoded PDF file."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib import colors
            from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
            from reportlab.lib.styles import getSampleStyleSheet
        except ImportError:
            return self._render_csv(records)
        columns = self._get_columns(records)
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        styles = getSampleStyleSheet()
        elements = [
            Paragraph(self.name, styles['Title']),
            Paragraph('Generated: %s' % fields.Datetime.now(), styles['Normal']),
        ]
        data = [[label for _, label in columns]]
        for record in records:
            row = []
            for fname, _label in columns:
                value = getattr(record, fname, '')
                if value and hasattr(value, 'name'):
                    value = value.name
                row.append(str(value or ''))
            data.append(row)
        table = Table(data)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        elements.append(table)
        doc.build(elements)
        buffer.seek(0)
        return base64.b64encode(buffer.read())

    def action_download(self):
        """Return a download URL for the generated file."""
        self.ensure_one()
        if self.history_id:
            self.history_id.sudo().write({
                'downloaded_by': self.env.user.id,
                'download_count': self.history_id.download_count + 1,
            })
        return {
            'type': 'ir.actions.act_url',
            'url': '/web/content?model=rgr.report.job&id=%d&field=file_data&filename=%s&download=true' % (
                self.id, self.file_name or 'report',
            ),
            'target': 'self',
        }
